### ISSUE TITLE
No Audio: MAG Z690 TOMAHAWK WIFI DDR4 & how to build info request

### ISSUE THREAD

**Issue by fubar-1** [alsa-project/alsa-ucm-conf#189] opened 2022-07-14 21:58 UTC
My MAG Z690 TOMAHAWK WIFI DDR4 motherboard has no alsa audio support.

It looks like the realtek-alc4080 audio chip is supported, just not on this motherboard due to a missing entry in `USB-Audio.conf`.
The USB audio device id is `0db0:b202`.
Currently it just displays as `USB Audio` and doesn't function at all.
This device works under windows so the hardware is functioning but not using any linux distro I've tried.

I attempted to address this myself, by downloading `https://github.com/alsa-project/alsa-ucm-conf/releases/tag/v1.2.7.2`, copying it to `/usr/share/alsa` (preserving simlinks of course) and editing `ucm2/USB-Audio/USB-Audio.conf`, changing line 46 to read `		Regex "USB((0b05:(1996|1a2[07]))|(0db0:(1feb|419c|a073|b202)))"`.
However, when I execute `sudo alsa force-reload` it generates parsing errors and `pactl list sinks` does not show any changes to the device properties as expected.

Can someone please explain what I need to do to get this device working?  Am I on the right track?  Do I need to rebuild alsa from github?  It's not clear and I'm not seeing build instructions.  I've been struggling with this for quite some time so any help would be appreciated.

I will PR the fix back to this repo once its working.

**Comment by perexg** [comment] 2022-07-27 09:01
Could you show the error when you use the `alsaucm -c hw:0 dump text` command with your change (replace 0 with the proper alsa card number - `aplay -l` may help)?

**Comment by RomanAverin** [comment] 2022-08-15 18:45
I have the same problem with the ALC4080
`# alsaucm -c hw:0 dump text`
```
ALSA lib parser.c:244:(error_node) UCM is not supported for this HDA model (HDA Intel PCH at 0x4014218000 irq 173)
ALSA lib main.c:1541:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -6
alsaucm: error failed to open sound card hw:0: No such device or address
```

**Comment by yhojann-cl** [comment] 2022-08-26 19:42
Similar issue here:

- https://github.com/alsa-project/alsa-ucm-conf/issues/186
- https://github.com/alsa-project/alsa-ucm-conf/issues/172
- https://bugs.launchpad.net/ubuntu/+source/alsa-driver/+bug/1978988

The problem is realtek-alc4080 audio chip dettection, msi came up with the great idea of giving a different hardware id to the same chip for max wifi boards.

**Comment by bcmedeiros** [comment] 2022-08-28 15:26
Same USB device here, `0db0:b202`, this change fixed the front panel for me:
```
--- ucm2/USB-Audio/USB-Audio.conf	2022-08-28 22:47:32.816348114 +0800
+++ /usr/share/alsa/ucm2/USB-Audio/USB-Audio.conf	2022-08-28 23:25:02.062267035 +0800
@@ -42,7 +42,8 @@
 		# 0db0:1feb MSI Edge Wifi Z690
 		# 0db0:419c MSI MPG X570S Carbon Max Wifi
 		# 0db0:a073 MSI MAG X570S Torpedo Max
-		Regex "USB((0b05:(1996|1a2[07]))|(0db0:(1feb|419c|a073)))"
+                # 0db0:b202 MSI MAG Z690 Tomahawk Wifi
+		Regex "USB((0b05:(1996|1a2[07]))|(0db0:(1feb|419c|a073|b202)))"
 	}
 	True.Define.ProfileName "Realtek/ALC4080"
 }
```

**Comment by motomyslen** [comment] 2022-08-28 18:56
I have USB device with id `0db0:a073`. I tried with v1.2.7.2 but it didn't work.

@bcmedeiros did you do something else beside updating USB-Audio.conf and reloading alsa?

**Comment by brunojcm-vgw** [comment] 2022-08-28 19:09
No, that's all I did.
Mic volume is very low, even if I set volume beyond 100%, so still not usable.
Tested the mic in the back panel, this one has no input at all.

I'm currently learning how the sound stack works on Linux, hopefully I'll find a solution eventually.

**Comment by bcmedeiros** [comment] 2022-08-28 19:12
No, that's all I did.
Mic volume is very low, even if I set volume beyond 100%, so still not usable.
Tested the mic in the back panel, this one has no input at all.

I'm currently learning how the sound stack works on Linux, hopefully I'll find a solution eventually.

**Comment by perexg** [comment] 2022-08-31 13:15
I added the USB ID in the above commit 730cdc7659efb9f22e985962effb911823c0d7a3 .

There are massive updates in the current UCM tree for ALC4080, if you like to give a test.

**Comment by perexg** [comment] 2022-09-07 12:10
I'm closing this right now - refer to https://github.com/alsa-project/alsa-ucm-conf/blob/master/ucm2/DEBUG.md for hints to debug the eventual issues.

**Closed by perexg** 2022-09-07 12:10 UTC

**Comment by Iss-in** [comment] 2023-02-17 12:49
same issue with mag b650 tomahawk, audio work now after adding device, but mic is indeed with very low sound

**Comment by tonatiuhmira** [comment] 2023-03-13 00:24
Hi, I'm not dev but I wanted to add that for ASUS ROG STRIX B650E-F GAMING WIFI, the device is `0b05:1a52` and the regex expression can be matched with 

`Regex "USB((0414:a00e)|(0b05:(1996|1a(16|2[07]|52)))|(0db0:(005a|151f|1feb|419c|82c7|a073|a47c|b202|d6e7)))"`

Microphone was not working before of this.

Still, if I connect the front headphone with mic, then the back mic is disabled, but if I unplug the front jack, the back mic stays disabled until next reboot. Should I open a new bug?

**Comment by ricciolino** [comment] 2023-11-28 11:46
I'm currently on Ubuntu 22.04 's alsa-ucm-conf 1.2.10 with a 0db0:b202 device (MAG Z690 TOMAHAWK WIFI DDR5) but headphone AUX jack support from the frontal chassis does not work, does someone know why?

(rear AUX jack is working properly)
