### ISSUE TITLE
Add support for AMD ACP Microphone devices for Yellow Carp platform

### ISSUE THREAD

**Issue by vijendarmukunda** [alsa-project/alsa-ucm-conf#136] opened 2022-01-27 03:43 UTC
We have tried to add similar changes which were applied for Renoir platform for YC platform by following below link.
https://github.com/alsa-project/alsa-ucm-conf/issues/54

But we are unable to create links.

Without ALSA UCM changes, we are able to observe similar issues earlier reported on Renoir platform as mentioned below.
1) Fallback profile is getting loaded and capture endpoint name is not listed as "Digital Microphone"
2) Mic Mute Led button is not reflected with Mute status.

Attached pa-info and alsa info output.
[painfo.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7947396/painfo.txt)
[alsa-info.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7947401/alsa-info.txt)
a

**Comment by perexg** [comment] 2022-01-27 20:53
Could you test changes in the above PR #138?

**Comment by vijendarmukunda** [comment] 2022-01-28 05:14
will verify the changes and let you know the result

**Comment by superm1** [comment] 2022-01-31 18:11
I had some test on an upcoming platform that uses this, and I can confirm that this is fixed:
> Fallback profile is getting loaded and capture endpoint name is not listed as "Digital Microphone"

However the mic mute LED doesn't work by default.  So I ran `alsactl clean` and rebooted the machine.
Here is the logs from muting or not muting in the GUI:
[painfo_not_muted_logs.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7973116/painfo_not_muted_logs.txt)
[pactl_list_sources_muted.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7973117/pactl_list_sources_muted.txt)
[pactl_list_sources_not_muted.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7973118/pactl_list_sources_not_muted.txt)
[painfo_muted_logs.txt](https://github.com/alsa-project/alsa-ucm-conf/files/7973119/painfo_muted_logs.txt)


Another interesting thing I found by default in the mixers that there is a "Capture" source that is enabled.
![image](https://user-images.githubusercontent.com/494526/151848370-8e78029d-cd7d-428a-8d81-37ce9e083b63.png)
If I disable that source like this:
![image](https://user-images.githubusercontent.com/494526/151848403-12015cce-329f-4a6d-af34-b0ab2d8a3796.png)

Then the GUI starts working for controlling mic mute LED.

**Comment by perexg** [comment] 2022-01-31 18:40
It's correct behavior. Mic mute LED is connected to two paths - the software defined Mic LED mixer control and HDA capture control by default. Both must be off to turn on the mic mute LED.

The mixer paths may be controlled using pavucontrol or any other tool for the pulseaudio/pipewire configuration (select the input path + mute sound button).

**Comment by superm1** [comment] 2022-01-31 18:55
Yeah, from pavucontrol if I go and mute **both** the "Family 17h (Models 10h-1fh) HD Audio Controller Headphones Stereo Microphone" and the "Family 17h (Models 10h-1fh) HD Audio Controller Digital Microphone" from `pavucontrol` then I can observe the LED does turn on.  I guess we can close this then.

**Comment by superm1** [comment] 2022-01-31 18:59
BTW - that Family ### (Models ###) business is completely wrong - this is a family 19h model 44h.  Where does it populate that from?

**Comment by perexg** [comment] 2022-01-31 19:24
I think that those strings are from udev - `udevadm info /sys/class/sound/card0` (maybe another card).

**Comment by superm1** [comment] 2022-01-31 19:55
Ah thanks, it looks like they pull from the PCI database.  
>E: ID_MODEL_FROM_DATABASE=Family 17h (Models 10h-1fh) HD Audio Controller

I'll submit a request there to make them more generic.

@vijendarmukunda please close this issue as Jaraslov committed the fix above.

**Closed** 2022-01-31 20:41 UTC
