### ISSUE TITLE
Asus ROG Strix B660-F (ALC4080) output issue: No audio front headphone, No audio S/PDIF

### ISSUE THREAD

**Issue by RomanAverin** [alsa-project/alsa-ucm-conf#205] opened 2022-08-26 22:31 UTC
I have problems playing audio from the front headphone jack, as well as S/PDIF. 
Kernel-5.19.4, Fedora 36, X11, Gnome 42

1. usb-device detect as `Bus 001 Device 004: ID 0b05:1a16 ASUSTek Computer, Inc. USB Audio`
2. Sound cards device by ` arecord -l `
```
**** List of CAPTURE Hardware Devices ****
card 0: Audio [USB Audio], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: Audio [USB Audio], device 1: USB Audio [USB Audio #1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: Audio [USB Audio], device 2: USB Audio [USB Audio #2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: J250a [Jabra UC VOICE 250a], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

3. Info from `alsa-info.sh` uploaded 
[http://alsa-project.org/db/?f=4376afd5f9282787f5ce07b8dd473e48639b6201](http://alsa-project.org/db/?f=4376afd5f9282787f5ce07b8dd473e48639b6201)
4. Trying to change the device id in the `/usr/share/alsa/ucm2/USB-Audio/Realtek/ALC4080.conf` on my id `Regex "USB(0b05:1a16)"` (default 0b05:1996)

**Comment by RomanAverin** [comment] 2022-08-26 22:51
I think I fixed it.
On `/usr/share/alsa/ucm2/USB-Audio/USB-Audio.conf` add id `0b05:1a16`
`Regex "USB((0b05:(1a16|1996|1a2[07]))|(0db0:(1feb|419c|a073)))"`

**Comment by RomanAverin** [comment] 2022-08-26 22:59
Made pull request

**Comment by RomanAverin** [comment] 2022-08-31 12:50
After a few days of testing, I found a problem after sleep. No sound from SPDIF

**Comment by perexg** [comment] 2022-08-31 13:06
This problem does not seem related to UCM. It looks like a driver problem - you may confirm that the S/PDIF device is not working after sleep using the native ALSA devices and tools (e.g. `speaker-test -D hw:0,3`) and if it's confirmed, report your issue to kernel's bugzilla - https://bugzilla.kerne.org (Audio group).

**Comment by perexg** [comment] 2022-09-07 11:52
There are some cleanups in the current repository for ALC4080, so you may like to give a check - https://github.com/alsa-project/alsa-ucm-conf/blob/master/ucm2/DEBUG.md .

New USB ID was merged in https://github.com/alsa-project/alsa-ucm-conf/pull/206 .

Closing now. Reopen this or create a new issue, if you find a problem.

**Closed by perexg** 2022-09-07 11:52 UTC
