### ISSUE TITLE
ALC4080 - ASRock X670E Taichi 

### ISSUE THREAD

**Issue by hendrikb-101** [alsa-project/alsa-ucm-conf#229] opened 2022-10-13 07:40 UTC
This board's ALC4082 seems to be sitting here:
`26ce:0a06 Generic USB Audio`

After trying out the latest UCM configuration I also tried adding this to my USB-Audio.conf:
`# 26ce:0a06 ASRock X670E Taichi`
`Regex "USB((26ce:0a06)|(0414:a00e)|(0b05:(1996|1a(16|2[07])))|(0db0:(005a|151f|1feb|419c|82c7|a073|a47c|b202)))"`

but no dice (still recognized as "Generic USB Audio" and ports don't work). Sound works in Windows 11 and manually playing a sound like that works:
`aplay -D plughw:Audio,1 /usr/share/sounds/alsa/Front_Left.wav    ` 

Is there anything else different on this board besides the device's id?!

This is my [alsa-info.txt](https://github.com/alsa-project/alsa-ucm-conf/files/9771968/alsa-info.txt).

**Comment by perexg** [comment] 2022-10-13 08:02
What does print `alsaucm -c hw:Audio dump text` command with your modified conf file?

**Comment by hendrikb-101** [comment] 2022-10-13 08:52
This is [alsaucm -c hw:Audio dump text](https://github.com/alsa-project/alsa-ucm-conf/files/9772505/alsaucm_-c_hw_Audio_dump_text.txt) and there's the output of `alsaucm -c hw:Audio set _verb HiFi`:
```ALSA lib main.c:826:(execute_sequence) unable to execute cset 'name='Line Capture Switch',index=0 off'
ALSA lib main.c:2573:(set_verb_user) error: failed to initialize new use case: HiFi
alsaucm: error failed to set _verb=HiFi: No such file or directory
```

**Comment by perexg** [comment] 2022-10-13 09:13
Could you try to comment (add `#` as the first char on the line) the SectionDevice blocks in `ALC4080-HiFi.conf`  until the `alsaucm -c hw:Audio set _verb HiFi` succeeds ? I don't see the real problem from this vague error message unfortunately.

Also, the firmware for this hw creates only two capture devices. It would be nice, if you can test all PCM devices (see `aplay -l` and `aplay -c` for the list of available devices) and related mixer controls (`alsamixer -D hw:Audio`).

**Comment by hendrikb-101** [comment] 2022-10-13 13:01
welp, I made a mistake pasting the error last time (triple ` requires a line break apparently). The full error message is this:
```
ALSA lib main.c:826:(execute_sequence) unable to execute cset 'name='Line Capture Switch',index=0 off'
ALSA lib main.c:2573:(set_verb_user) error: failed to initialize new use case: HiFi
alsaucm: error failed to set _verb=HiFi: No such file or directory
```

Accordingly, commenting out this block made the command succeed:
```
#If.line1 {
#	Condition {
#		Type String
#		Empty "${var:Line1Name}"
#	}
#	False.SectionDevice."Line1" {
#		Comment "${var:Line1Name}"
#
#		EnableSequence [
#			cset "name='${var:Line1Mixer} Capture Switch',index=${var:Line1Mindex} on"
#		]
#
#		DisableSequence [
#			cset "name='${var:Line1Mixer} Capture Switch',index=${var:Line1Mindex} off"
#		]
#
#		Value {
#			CapturePriority 100
#			CapturePCM "${var:Line1PCM}"
#			JackControl "${var:Line1Jack}"
#			CaptureMixerElem "${var:Line1Mixer},${var:Line1Mindex}"
#		}
#	}
#}
```
However, I can't get `aplay -D plughw:Audio,1 /usr/share/sounds/alsa/Front_Left.wav` to play anything now and I don't know how I would test the devices?

**Comment by perexg** [comment] 2022-10-17 10:31
If you get busy errors, you need to stop the pulseaudio server or the pipewire server to test the raw ALSA devices. Also, check the mixer settings (alsamixer).

**Comment by IsaacVaughn** [comment] 2022-11-05 22:35
I am having the same problem. I can head "aplay -D plughw:Audio,1 /usr/share/sounds/alsa/Front_Left.wav", put pulseaudio gives "No UCM verb is valid for hw:0". I also get the same error when running "set _verb=HiFi", and deleting the line1 config makes the error go away. After doing so, I cam able to get sound from aplay after using alsamixer to unmute the audio again.

By muting and unmuting channels, I have confirmed that "PCM 1" corresponds to the front headphone jack.

However, pulseaudio is now failing to find any audio at all.
```
Nov 05 18:28:40 manjaro pulseaudio[436340]: Failed to load module "module-alsa-card" (argument: "device_id="0" name="usb-Generic_USB_Audio-00" card_name="alsa_card.usb-Generic_USB_Au>
```

**Comment by IsaacVaughn** [comment] 2022-11-05 23:13
I was able to get pulseaudio working by deleting all ALC4080 configs except the headphone and speaker sections. I have yet to narrow down the problem any further than that.:

**Comment by perexg** [comment] 2022-11-15 17:03
Could you try the above change? You may download USB-Audio.conf and ALC4080-HiFi.conf using those links:

https://raw.githubusercontent.com/perexg/alsa-ucm-conf/issue/229/ucm2/USB-Audio/USB-Audio.conf
https://raw.githubusercontent.com/perexg/alsa-ucm-conf/issue/229/ucm2/USB-Audio/Realtek/ALC4080-HiFi.conf

**Comment by hendrikb-101** [comment] 2022-11-16 09:54
Does not yet work for me, but does give a more detailed problem description.

alsaucm -c hw:Audio set _verb HiFi:
'''ALSA lib main.c:826:(execute_sequence) unable to execute cset 'name='Line Capture Switch',index=0 off'
ALSA lib main.c:2573:(set_verb_user) error: failed to initialize new use case: HiFi
alsaucm: error failed to set _verb=HiFi: No such file or directory'''

Also:
[alsaucm -c hw_Audio dump text.txt](https://github.com/alsa-project/alsa-ucm-conf/files/10020425/alsaucm.-c.hw_Audio.dump.text.txt)

**Comment by perexg** [comment] 2022-11-16 10:39
I've updated my test repo. Please, download again and retest. Thanks.

**Comment by hendrikb-101** [comment] 2022-11-16 11:24
That's it! Both front & rear audio output and input work.

Automatically switches for output when I plug the headset in front/rear, but doesn't do so for the Mic. Instead I now have 2 mic inputs and have to manually c

**Comment by perexg** [comment] 2022-11-16 11:40
I think that you see an issue in the alsa-lib-1.2.8 code which was fixed in https://github.com/alsa-project/alsa-lib/commit/1b436862ed6253629d79edc2e09826efd4e0f4e3 . Could you try to switch priorities for the Mic1/Mic2 devices in Realtek/ALC4080-HiFi.conf? Switch CapturePriority values 400 <-> 300.

**Comment by hendrikb-101** [comment] 2022-11-16 11:56
After switching priorities:
- "Microphone2" always stays listed as an input device as if it was plugged in.
- When plugging in the mic into the rear connector, "Microphone" (1) appears and is selected as input device.
This solves the issue in practice! I don't know if Mic2 should disappear after disconnecting the mic from the front connect or?

What's PA/PW? The input on the rear panel has a 'Mic' icon next to it, as does the front jack on the case (...which is a Fractal Torrent). I have attached screenshots from the mainboards manual explaining the ports.
![Screenshot_20221116_125406](https://user-images.githubusercontent.com/58671762/202174267-47282ccf-277d-4e9a-bc6c-1b7ca362b9ba.png)

![Manual-1](https://user-images.githubusercontent.com/58671762/202174262-2b65866f-4acc-44a4-bd1f-ad10855e1ff4.png)

**Comment by perexg** [comment] 2022-11-16 11:58
PA/PW - Pulseaudio/Pipewire

Which microphone device in the sound server is for the front panel ?

**Comment by perexg** [comment] 2022-11-16 12:00
> I don't know if Mic2 should disappear after disconnecting the mic from the front connect or?

Basically, the jack detection information is wrongly parsed without patched alsa-lib, thus the Microphone2 device is present all time, but by priority, the Microphone device is selected.

**Comment by perexg** [comment] 2022-11-16 12:10
Another version for tests is available. Could you check if the names corresponds to the function? No priority changes are required - I swapped the whole device definitions.

**Comment by IsaacVaughn** [comment] 2022-11-24 18:41
Is there a way to test without having a microphone? I am willing to help test, but only have an analog headset, no microphones.

**Comment by abonny** [comment] 2022-12-03 18:24
I have this same motherboard but a bigger problem.  My boot hangs indefinitely.  I get a handful of (EFI) errors but here's the final error it hangs on:  `snd_hda_intel 0000:5a:00.6: no codecs found!`

I tried adding this:  `options snd-hda-intel enable=0,1,0` to file `/etc/modprobe.d/alsa-base.conf` and that didn't change any behavior (Reference1).

I am running "Kubuntu 22.04 LTS", fully up to date.  What's crazy is the "live" edition and recovery both boot.  I can literally boot recovery, then "resume" normal boot and get into the desktop.  This makes me wonder if it's a race condition.

Reference1: https://bbs.archlinux.org/viewtopic.php?id=196996

**Comment by perexg** [comment] 2022-12-03 18:40
> I have this same motherboard but a bigger problem. My boot hangs indefinitely. I get a handful of (EFI) errors but here's the final error it hangs on: snd_hda_intel 0000:5a:00.6: no codecs found!

This is correct. ALC4080 is an USB soundcard. The analog HDA PCI bridge is not used on those motherboards. Try the updated UCM configuration.

**Comment by abonny** [comment] 2022-12-03 20:19
> > I have this same motherboard but a bigger problem. My boot hangs indefinitely. I get a handful of (EFI) errors but here's the final error it hangs on: snd_hda_intel 0000:5a:00.6: no codecs found!
> 
> This is correct. ALC4080 is an USB soundcard. The analog HDA PCI bridge is not used on those motherboards. Try the updated UCM configuration.

Forgive me but can you walk me through the full paths on my machine and where do I get the latest "UCM" configuration?  Is it `USB-audio.conf` that I'm replacing?  If so I have that file in many places:
```
/snap/gnome-3-38-2004/112/usr/share/alsa/cards/USB-Audio.conf
/snap/gnome-3-38-2004/119/usr/share/alsa/cards/USB-Audio.conf
/usr/share/alsa/cards/USB-Audio.conf
/usr/share/alsa/ucm2/USB-Audio/USB-Audio.conf
/usr/share/alsa/ucm2/conf.d/USB-Audio/USB-Audio.conf
```
Thanks

**Comment by abonny** [comment] 2022-12-08 01:19
I replaced `USB-Audio.conf` (from https://raw.githubusercontent.com/perexg/alsa-ucm-conf/issue/229/ucm2/USB-Audio/USB-Audio.conf) in the last three places above (snap shouldn't matter, FYI one file was a symlink to another).  And that made no difference.

**Comment by perexg** [comment] 2023-02-07 09:30
The latest ALC4080 config is working for most of users (I'm constantly adding new USB IDs). Please, create another issue with full _description_ for your problem.

**Comment by Zamundaaa** [comment] 2023-03-18 17:32
> Could you try the above change? You may download USB-Audio.conf and ALC4080-HiFi.conf using those links:
> 
> https://raw.githubusercontent.com/perexg/alsa-ucm-conf/issue/229/ucm2/USB-Audio/USB-Audio.conf https://raw.githubusercontent.com/perexg/alsa-ucm-conf/issue/229/ucm2/USB-Audio/Realtek/ALC4080-HiFi.conf

@perexg the original issue (detection as "Generic USB Audio" and no audio output) still exists on master, and testing these files locally they make the sound on this mainboard work flawlessly for me. Can those changes please be incorporated into the master?

**Comment by abonny** [comment] 2023-03-21 22:46
Any idea how long before this ends up in popular distros?  Beyond merging to `master` did any code change since Dec 2022?

**Comment by Zamundaaa** [comment] 2023-03-22 19:24
@perexg S/PDIF and line out work without a problem., but the front panel output doesn't make a sound. It does detect that the headphones are plugged in though. I don't have any microphones here so I can't test that atm.

**Comment by meberlein** [comment] 2023-07-05 20:58
Unfortunately with the latest config from this thread still no luck with the headphone output on the ASRock x670e Taichi.

Aplayer with plughw works although only mono it seems. 

Not sure if maybe the relatively new DAC in the chain would be the source any issues?
![image](https://github.com/alsa-project/alsa-ucm-conf/assets/526337/83d1fc3e-f3a2-44c6-b11a-d242caefc700)

Sharing alsa info as well
[alsa-info.txt](https://github.com/alsa-project/alsa-ucm-conf/files/11962020/alsa-info.txt)

**Comment by hwchong** [comment] 2023-07-09 01:55
@perexg just out of curiosity why is this issue still open? the changes you posted seems to enable this to be fixed. I have applied it to my own branch. Should I do a PR and have it merged to master? https://github.com/hwchong/alsa-ucm-conf/commit/3ec7e6e2a61240764b77c30892f0bc56803799cc

**Comment by Chevek** [comment] 2023-08-23 10:17
I also have the Asrock x670e Taichi. This indeed fix the no sound issue using fedora 38 :
I've copy those 2 files https://github.com/alsa-project/alsa-ucm-conf/issues/229#issuecomment-1315611625
in /usr/share/alsa/ucm2/USB-Audio
& /usr/share/alsa/ucm2/USB-Audio/Realtek/

Thank you, I hope this will be released ASAP.

**Comment by jonasdutra** [comment] 2023-10-29 22:44
> I also have the Asrock x670e Taichi. This indeed fix the no sound issue using fedora 38 : I've copy those 2 files [#229 (comment)](https://github.com/alsa-project/alsa-ucm-conf/issues/229#issuecomment-1315611625) in /usr/share/alsa/ucm2/USB-Audio/USB-Audio.conf & /usr/share/alsa/ucm2/USB-Audio/Realtek/ALC4080-HiFi.conf
> 
> Thank you, I hope this will be released ASAP.

Chevek, solved no sound in SPDIF ?

**Comment by Chevek** [comment] 2023-11-05 22:38
Sorry, I do not use S/PDIF.

**Comment by millma** [comment] 2023-11-05 22:47
I have one of these boards and can get access to a S/PDIF adapter to test, if that would be helpful.

**Comment by abonny** [comment] 2023-11-10 18:00
Audio now works for me using Kubuntu 22.04.3 LTS.  It's the third edit (22.04**.3**) of that O.S. that made the difference

**Comment by jonasdutra** [comment] 2023-11-10 20:07
> Audio now works for me using Kubuntu 22.04.3 LTS.  It's the third edit (22.04**.3**) of that O.S. that made the difference

SPDIF ?

**Comment by abonny** [comment] 2023-11-10 23:49
> > Audio now works for me using Kubuntu 22.04.3 LTS.  It's the third edit (22.04**.3**) of that O.S. that made the difference
> 
> SPDIF ?

Sorry I don't have an easy way to test SPDIF.  This is the jack directly to the right, line out

**Comment by ZVNexus** [comment] 2023-11-27 06:49
@perexg @jonasdutra FYI I tested https://github.com/alsa-project/alsa-ucm-conf/commit/4766b40057261ca84938413fe9c9986ecd2256b1 on my ASRock X670E Taichi and I am able to confirm this fixes SPDIF output on the board (tested with Sennheiser RS 185's), this can be closed.

**Closed** 2024-01-09 14:32 UTC
