### ISSUE TITLE
i have some technical issues with the Arturia minifuse 1 sound card.  i would like help with converting the minifuse 2 UCM config to work with minifuse 1

### ISSUE THREAD

**Issue by Ali32bit** [alsa-project/alsa-ucm-conf#220] opened 2022-09-30 21:38 UTC
greetings.        so i have a sound card with multiple outputs and some loop back channels.  it is USB complaint but those extra bells and whistles  cause ALSA to think its a surround sound device when its actually just stereo.  and this actually impacts the sound when i play games on it cause sounds from behind are basically muted.   and thats the case with some music too but less obvious
here is what alsa_info generated for me too : 

http://alsa-project.org/db/?f=b6db7723ffa65f32b93297109bf1f8e4d853cf4e

there should already be a minifuse 2 setup so if possible please adapt it to minifuse 1 or help me convert and install it myself.     the hardware is mostly the same but it has 1 input instead of 2  and no extra midi ports in the back.

**Comment by nodens** [comment] 2022-10-06 19:28
Please try my branch from the PR above, which is my attempt at adding such support.
The idea here is that from UCM point of view, it's exactly the same as Minifuse 2 with one less input (and so no physical stereo input, but there is still a stereo loopback).

**Comment by nodens** [comment] 2022-10-10 13:10
Note: I've been in touch with @Ali32bit on Reddit, and they seem to have issues testing my fix, so:

Some more info to make it easier for you to test, also because it might help other people getting here after a web search:
- get my branch from https://github.com/nodens/alsa-ucm-conf/tree/add_arturia_minifuse_1_use_case
- copy the `ucm2` tree to your system (probably `/usr/share/alsa/ucm2`, and of course it's probably better to make a backup beforehand, but it's easy to get back to your system version by removing the ucm2 folder on your system and reinstall the package containing it: on Debian/ubuntu-like systems it's named `alsa-ucm-conf`). See also information on the `README.md` file.
- unplug / replug your minifuse
- check with pavucontrol if you see the correct profiles in the configuration tab (or equivalent).

If you don't see any change, you can try to restart your sound daemons (eg pulseaudio or pipewire + pipewire-pulse + wireplumber), or even reboot your system to be sure, and we'll check from there…  It's totally possible I forgot something :)

**Comment by nodens** [comment] 2022-10-11 20:28
Either my PR is not working, or maybe pulseaudio/pipewire config is interfering… 

What do you see in pavucontrol in the configuration tab ? For each device, you should be able to set a profile, what are they for the minifuse?

To see what's going on, other helpful stuff:

- run `alsaucm reload` and check for errors (including with `journalctl` / `journalctl --user`)
- check the number or short name of your card with `aplay -l` and dump the UCM config:
  `alsaucm -c hw:<number or short name> dump text`. If Minifuse 1 follow minifuse 2 naming, following should work in your case:
  `alsaucm -c hw:M1 dump text`

And post output of the dump.

**Comment by Ali32bit** [comment] 2022-10-12 09:36
i did the installation on 2 different  distros with the same result so i doubt its a problem from my system side unless i am doing something wrong. 
  
alsaucm reload says this :                     _ALSA lib conf.c:2007:(_snd_config_load_with_include) _toplevel_:1:1:Unexpected char
ALSA lib utils.c:375:(uc_mgr_config_load_into) could not load configuration file /usr/share/alsa/ucm2/conf.d/HDA-Intel/HDA-Intel.conf
ALSA lib parser.c:2791:(load_toplevel_config) error: could not parse configuration for card hw:1
ALSA lib main.c:1541:(snd_use_case_mgr_open) error: failed to import hw:1 use case configuration -22
alsaucm: error failed to open sound card hw:1: Invalid argument_   

aplay- says this :  _**** List of PLAYBACK Hardware Devices ****
card 0: M1 [MiniFuse 1], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 0: CX20751/2 Analog [CX20751/2 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0 *]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0_

the dump command said this : _ALSA lib conf.c:2007:(_snd_config_load_with_include) _toplevel_:1:1:Unexpected char
ALSA lib utils.c:375:(uc_mgr_config_load_into) could not load configuration file /usr/share/alsa/ucm2/conf.d/USB-Audio/USB-Audio.conf
ALSA lib parser.c:2791:(load_toplevel_config) error: could not parse configuration for card hw:M1
ALSA lib main.c:1541:(snd_use_case_mgr_open) error: failed to import hw:M1 use case configuration -22
alsaucm: error failed to open sound card hw:M1: Invalid argument_

**Comment by nodens** [comment] 2022-10-12 13:58
Ok, so it must be an issue with my changes. I'll have a look in the next few days.

**Comment by Ali32bit** [comment] 2022-10-12 19:18
from what my package manager says  the ALSA ucm  conf version is  1.2.7.2-1     ,   an issue with the intergrated sound card seems plausible too since its not the usual stock brand in most lap tops.   i think it was  called conexant  smart audio or something in windows.       i did just re install the stock version then tried to add the configs again.  same result.       running the command for the stock version says this :  _ALSA lib parser.c:244:(error_node) UCM is not supported for this HDA model (HDA Intel PCH at 0xdf328000 irq 132)
ALSA lib main.c:1541:(snd_use_case_mgr_open) error: failed to import hw:1 use case configuration -6
alsaucm: error failed to open sound card hw:1: No such device or address_

**Comment by nodens** [comment] 2022-10-16 16:13
I tested with my Minifuse 2 by changing the pci id for the needle instruction on my system, so it would load the M1 profile on the M2.

Turns out I forgot to remove a reference to Line3 which doesn't exist on a M1.

Please test again !

**Comment by Ali32bit** [comment] 2022-10-16 19:07
it didnt seem to change much,   i still get an error saying it cant load the configuration and there is an invalid argument.

_

> ALSA lib conf.c:2007:(_snd_config_load_with_include) _toplevel_:1:1:Unexpected char
> ALSA lib utils.c:375:(uc_mgr_config_load_into) could not load configuration file /usr/share/alsa/ucm2/conf.d/USB-Audio/USB-Audio.conf
> ALSA lib parser.c:2791:(load_toplevel_config) error: could not parse configuration for card hw:0
> ALSA lib main.c:1541:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -22
> alsaucm: error failed to open sound card hw:0: Invalid argument

_

**Comment by nodens** [comment] 2022-10-17 08:04
Well, there I'm a a loss, I don't see why you'd get this error with the last version. When I tested to load the previous version, I had an explicit error about Line3 not existing, which made sense. Here it looks like something else is wrong. Are you sure you copied the file directly ?

I just use rsync from the git repo on my system, after copying /usr/share/alsa to be able to reset:

`sudo cp -a /usr/share/alsa /usr/share/alsa.bak` (before messing up with it of course, but you can always reinstall alsa-ucm-conf package)
`sudo rsync -rcv --delete /home/nodens/src/alsa/alsa-ucm-conf/ucm2/USB-Audio/ /usr/share/alsa/ucm2/USB-Audio/ --dry-run` (here I know I only touched USB-Audio, but maybe you need to get the whole ucm2 directory, I can't say for manjaro). Remove the --dry-run if the files it create/delete is consistent. I remember having strange issue, and it took forever to realize I didn't copy the files at the right place (I created another `ucm2` subdir under the existing `ucm2` by mistake).

Also, the error you get is nothing like the one I got on my tests with the previous version:

```
~$ alsaucm -c hw:1 dump text
ALSA lib parser.c:1756:(verb_dev_list_add) error: unable to find device 'Line3'
ALSA lib parser.c:2057:(parse_verb_file) error: device management error in verb 'HiFi'
ALSA lib main.c:1541:(snd_use_case_mgr_open) error: failed to import hw:1 use case configuration -2
alsaucm: error failed to open sound card hw:1: No such file or directory
```

So I can help but think that something else is wrong here.

**Comment by Ali32bit** [comment] 2022-10-18 17:55
i am at a loss too.   i really do copy the folder to the correct place with cp command in the correct format,  and its detected too cause without those files i get a different error that they dont exist , i tried to install it again with a fresh manjaro install that i had,  same result.      i feel like something is still wrong that  we cant  see cause the hardware is slightly different.     just for reference it looks like this on windows in the sound settings : 

![Capture](https://user-images.githubusercontent.com/91943907/196507271-39f81f80-14be-4dae-b2ed-9484775072fb.PNG)
![Capture2](https://user-images.githubusercontent.com/91943907/196507293-35caf65d-bef8-4994-b197-e117d5c89caa.PNG)
 
something else is going wrong somewhere else, or maybe i am an idiot with the command line who knows.   the files are definitely in the right place in the file manager and in text editor i see all your changes,  what OS are you testing this on if you dont mind me asking ?

**Comment by perexg** [comment] 2022-10-19 08:08
The copy of the text files should be very straight. The "toplevel:1:1:Unexpected char" signalize that the files are not in the right format.

The commit 2942a766b805be3ee070c30f0d034ba8494a8db0 contains the "merged" support for Minifuse 1 and 2.

I added the latest config download info to README: 3ddd8b285fe578b66cacec7c5c6e6801144cf848 .

**Comment by nodens** [comment] 2022-10-19 12:36
Thanks, that's much cleaner than my naive attempt! :)

**Comment by Ali32bit** [comment] 2022-10-19 22:11
ah so it was a file format problem ?     how would i install it correctly then ?    the command in the  "read me" wont work for me.

i get an error like this :    _ar xvzf alsa-ucm-conf.tar.gz -C /usr/share/alsa --strip-components=1 "*/ucm" "*/ucm2"                                                      ✔ 
tar: Pattern matching characters used in file names
tar: Use --wildcards to enable pattern matching, or --no-wildcards to suppress this warning
tar: */ucm: Not found in archive
tar: Pattern matching characters used in file names
tar: Use --wildcards to enable pattern matching, or --no-wildcards to suppress this warning
tar: */ucm2: Not found in archive
tar: Exiting with failure status due to previous errors
    ~                                                   _
its saying it cant find the files even tough they exist in the archive , must be some kind of terminal thing i dont know about
     
sorry if i sound so noob like,  i am still  trying to wrap my head around commands.  
so far i have been installing it by extracting the archive then copying the files with cp or converting the archive to zip and using unzip command instead.    not sure how that would currupt the files tough.

**Comment by nodens** [comment] 2022-10-20 16:59
ha, that's a tar version or defaults issue.
Try to add `--wildcards` to the tar command, as the output suggest (error are helpful, promise!), like this:

```
sudo tar xvzf alsa-ucm-conf.tar.gz -C /usr/share/alsa --strip-components=1 --wildcards "*/ucm" "*/ucm2"
```
The problem is that tar doesn't know if you intend to search for file with `*` in their name (default) or to use `*` as a wildcard. With --wildcards you remove the ambiguity.

**Comment by Ali32bit** [comment] 2022-10-23 20:48
ayy now it works i think.  it says minifuse L/R instead of susrround.    peace achived

**Closed** 2022-10-23 20:50 UTC
